### ISSUE TITLE
lyve pilot registration does not attach to correct S3 URL

### ISSUE THREAD

**Issue by korenlev** [Seagate/cortx#471]
while cortx-GUI used to https://VM-IP:28100 , the registration process is trying (and failing ofc) to connect to 127.0.0.1:5000 for creating the new S3 account, suggest it should get the same $VM-IP from the browser

**Comment by korenlev** [comment]
csm_agent CRITICAL [rest_middleware] Unhandled Exception Caught: Cannot connect to host 127.0.0.1:5000 ssl:None [Connect call failed ('127.0.0.1', 5000)] #012 Traceback (most recent call last):#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection#012  File "/usr/lib64/python3.6/asyncio/base_events.py", line 794, in create_connection#012    raise exceptions[0]#012  File "/usr/lib64/python3.6/asyncio/base_events.py", line 781, in create_connection#012    yield from self.sock_connect(sock, address)#012  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 439, in sock_connect#012    return (yield from fut)#012  File "/usr/lib64/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb#012    raise OSError(err, 'Connect call failed %s' % (address,))#012ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 5000)#012#012The above exception was the direct cause of the following exception:#012#012Traceback (most recent call last):#012  File "csm/core/agent/api.py", line 303, in rest_middleware#012  File "csm/core/agent/api.py", line 273, in session_middleware#012  File "csm/core/agent/api.py", line 287, in permission_middleware#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 892, in _iter#012  File "csm/core/controllers/usl.py", line 115, in post#012  File "csm/core/services/usl.py", line 528, in 
csm_agent log here:
===============

post_register_device#012  File "csm/core/services/usl.py", line 483, in post_register_device#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection#012  File "/root/.local/lib/python3.6/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection#012aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:5000 ssl:None [Connect call failed ('127.0.0.1', 5000)]

**Comment by mukul-seagate11** [comment]
@kupranay, please take care of the issue

**Comment by kupranay** [comment]
Thanks @korenlev for raising the issue. UDX registration is not supported on OVA isntallation or VM. 
When you access UDX registration page through UI, it should show message that this feature is not available on the installation.
Please confirm if this message if not coming on UI as well as please share the  XHR copy or csm-agent.log file.

**Comment by korenlev** [comment]
Good to know guys, message does not display
Koren

בתאריך יום ג׳, 17 בנוב׳ 2020, 07:55, מאת kupranay ‏<notifications@github.com

**Comment by kupranay** [comment]
Thanks @korenlev , we will keep this issue open to check why message is not displayed. Please update the logs file if possible
@soniyamoholkar  please check why messages are not shown
